[package]
name = "ilmen-dot-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror ={ version = "1.0"}
anyhow = {version = "1.0"}
log = "0.4"
petgraph = {version = "0.6", features = ["serde-1"]}